server:
  port: 8080
spring:
  application:
    name: inventory application
  datasource:
    username: root
    password: admin123
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:5433/choreography
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
